### ISSUE TITLE
oAuth POST with File

### ISSUE THREAD

**Issue by jabramson623** [jrconlin/OAuthTestPage#1]
Trying to get this functioning with a file attachment.  Have any working examples of this?

**Comment by jrconlin** [comment]
Well, this is more of a test page for OAuth1.0a library authors. 

I'm not sure how the site you're trying to access wants you to provide the file content, but the body of the POST isn't really checked by OAuth normally, just the arguments associated with the POST. A site might want you to include a SHA hash of the file as a header to show that nothing changed that value, but, again, that's up to the site. 

May want to contact whoever's providing you the API to see what to do. 

Closing this since it's not really an issue with the test page.
